apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: monitoring-infrastructure
  labels:
    app: prometheus
    component: core
  annotations:
    prometheus.io/scrape: 'true'
    metallb.universe.tf/address-pool: production-public-ips
spec:
  type: LoadBalancer
  loadBalancerIP: 10.192.13.74
  ports:
    - port: 9090
      protocol: TCP
      name: webui
  selector:
    app: prometheus
    component: core
