apiVersion: v1
data:
  prometheus.yaml: |
    global:
      scrape_interval: 15s
      scrape_timeout: 10s
      evaluation_interval: 15s
    scrape_configs:
    - job_name: node
      honor_labels: true
      honor_timestamps: true
      scrape_interval: 15s
      scrape_timeout: 10s
      metrics_path: /metrics
      scheme: http
      static_configs:
      - targets:
        - your_node_exporter_machine:9100
    remote_write:
    - url: http://influxdb:8086/api/v1/prom/write?db=prometheus
      remote_timeout: 30s
      queue_config:
        capacity: 500
        max_shards: 1000
        min_shards: 1
        max_samples_per_send: 100
        batch_send_deadline: 5s
        min_backoff: 30ms
        max_backoff: 100ms
    remote_read:
    - url: http://influxdb:8086/api/v1/prom/read?db=prometheus
      remote_timeout: 5m
      read_recent: true    
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: prometheus-core
  namespace: monitoring-infrastructure
