---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: monitoring-infrastructure
  annotations:
    metallb.universe.tf/address-pool: production-public-ips
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: grafana
  type: LoadBalancer
  loadBalancerIP: 10.193.14.78
