---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc-prod
  namespace: monitoring-prod
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 20Gi
  storageClassName: csi-rbd-sc
