---
apiVersion: v1
kind: Service
metadata:
  name: influxdb
  namespace: influxdb-prod
  labels:
    app: influxdb
spec:
  clusterIP: None
  ports:
  - name: influxdb-port
    port: 8086
    targetPort: 8086
  selector:
    app: influxdb
