---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-database-500-pvc
  namespace: influxdb-prod
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 500Gi
  storageClassName: csi-rbd-sc
